Script started on Wed 27 Jan 2021 10:55:01 PM PST
]0;sdbrione@crystalcove:hw2[sdbrione@crystalcove hw2]$ gccls[Kgcc -ansi -std=c99 -Wall PhotoLab_v1.c -o PhotoLab_v1
]0;sdbrione@crystalcove:hw2[sdbrione@crystalcove hw2]$ ./PhotoLab_v1 
[H[2JWelcome to Photo Lab 2021 - v1!

--------------------------------------------

 1: Load PPM image
 2: Save image in PPM and JPEG format
 3: Run aging filter
 4: Run edge detection filter
 5: Run sharpen filter
22: Test all functions
99: Exit
--------------------------------------------

Please make your choice: 5
[H[2J"Sharpen" operation is done!
Welcome to Photo Lab 2021 - v1!

--------------------------------------------

 1: Load PPM image
 2: Save image in PPM and JPEG format
 3: Run aging filter
 4: Run edge detection filter
 5: Run sharpen filter
22: Test all functions
99: Exit
--------------------------------------------

Please make your choice: 22
[H[2Jlambo.ppm was read successfully!
"Aging" operation is done!
aging.ppm was saved successfully. 
aging.jpg was stored for viewing. 
Aging tested!

lambo.ppm was read successfully!
"Edge Detection" operation is done!
edge.ppm was saved successfully. 
edge.jpg was stored for viewing. 
Edge Detection tested!

lambo.ppm was read successfully!
"Sharpen" operation is done!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen tested!

Welcome to Photo Lab 2021 - v1!

--------------------------------------------

 1: Load PPM image
 2: Save image in PPM and JPEG format
 3: Run aging filter
 4: Run edge detection filter
 5: Run sharpen filter
22: Test all functions
99: Exit
--------------------------------------------

Please make your choice: 99
]0;sdbrione@crystalcove:hw2[sdbrione@crystalcove hw2]$ exit
exit

Script done on Wed 27 Jan 2021 10:55:47 PM PST
