Script started on Mon 15 Feb 2021 08:47:44 PM PST
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ make clean
rm -f *.o
rm -f *.a
rm -f PhotoLab_v2
rm -f PhotoLabTest
rm -f age.ppm
rm -f sharpen.ppm
rm -f edge.ppm
rm -f posterize.ppm
rm -f negative.ppm
rm -f noise.ppm
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ make 
gcc -Wall -ansi -std=c99 -c FileIO.c -o FileIO.o
gcc -Wall -ansi -std=c99 -c DIPs.c -o DIPs.o
gcc -Wall -ansi -std=c99 -c Advanced.c -o Advanced.o
ar rc libfilter.a DIPs.o Advanced.o
ranlib libfilter.a
gcc -Wall -ansi -std=c99 -c PhotoLab_v2.c -o PhotoLab.o
gcc -Wall -std=c99 PhotoLab.o FileIO.o -L. -lfilter -o PhotoLab_v2 -lm 
gcc -Wall -ansi -std=c99 -c -g -DDEBUG PhotoLab_v2.c -o PhotoLabTest.o
gcc -g -DDEBUG -Wall -std=c99 PhotoLabTest.o FileIO.o -L. -lfilter -o PhotoLabTest -lm
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ ./Pho
PhotoLabTest* PhotoLab_v2*  
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ ./PhotoLab_v2
Welcome to Photo Lab 2021 - v1!
-------------------------
 1: Load a PPM image
 2: Save the image in PPM and JPEG format
 3: Run aging filter
 4: Run edge detection filter
 5: Run sharpen filter
 6: Run noise filter
 7: Run posterize filter
 8: Run negative filter
22: Test all functions
99: Exit
--------------------------
Please make your choice: 22


pigeon.ppm was read successfully!
age.ppm was saved successfully. 
age.jpg was stored for viewing. 


pigeon.ppm was read successfully!
edge.ppm was saved successfully. 
edge.jpg was stored for viewing. 


pigeon.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 


pigeon.ppm was read successfully!
noise.ppm was saved successfully. 
noise.jpg was stored for viewing. 


pigeon.ppm was read successfully!
posterize.ppm was saved successfully. 
posterize.jpg was stored for viewing. 


pigeon.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 

-------------------------
 1: Load a PPM image
 2: Save the image in PPM and JPEG format
 3: Run aging filter
 4: Run edge detection filter
 5: Run sharpen filter
 6: Run noise filter
 7: Run posterize filter
 8: Run negative filter
22: Test all functions
99: Exit
--------------------------
Please make your choice: 99
Exiting program.
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ make Pho
PhotoLab.o          PhotoLabTest.o      PhotoLab_v2.c       
PhotoLabTest*       PhotoLab_v2*        PhotoLab_v2.script  
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ make PhotoLabo[KTest
make: `PhotoLabTest' is up to date.
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ ./Pho
PhotoLabTest* PhotoLab_v2*  
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ ./PhotoLabTest


pigeon.ppm was read successfully!
age.ppm was saved successfully. 
age.jpg was stored for viewing. 
Aging tested!

pigeon.ppm was read successfully!
edge.ppm was saved successfully. 
edge.jpg was stored for viewing. 
Edge Detection tested!

pigeon.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen tested!

pigeon.ppm was read successfully!
noise.ppm was saved successfully. 
noise.jpg was stored for viewing. 
Noise tested!

pigeon.ppm was read successfully!
posterize.ppm was saved successfully. 
posterize.jpg was stored for viewing. 
Posterize tested!

pigeon.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ touch Ad
Advanced.c  Advanced.h  Advanced.o  
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ touch Advanced.c
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ make Pho
PhotoLab.o          PhotoLabTest.o      PhotoLab_v2.c       
PhotoLabTest*       PhotoLab_v2*        PhotoLab_v2.script  
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ make PhotoLab_
PhotoLab_v2*        PhotoLab_v2.c       PhotoLab_v2.script  
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ make PhotoLab_v2
gcc -Wall -ansi -std=c99 -c Advanced.c -o Advanced.o
ar rc libfilter.a DIPs.o Advanced.o
ranlib libfilter.a
gcc -Wall -std=c99 PhotoLab.o FileIO.o -L. -lfilter -o PhotoLab_v2 -lm 
]0;sdbrione@crystalcove:hw3[sdbrione@crystalcove hw3]$ exit
exit

Script done on Mon 15 Feb 2021 08:48:52 PM PST
