Script started on Sun 07 Mar 2021 05:21:33 PM PST
]0;sdbrione@crystalcove:hw4[sdbrione@crystalcove hw4]$ make
gcc -ansi -std=c99 -Wall -c PhotoLab_v3.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -c Test.c -o Test.o
gcc -ansi -std=c99 -Wall -c DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c Advanced.c -o Advanced.o
ar rc libfilter.a Advanced.o DIPs.o
ranlib libfilter.a
gcc -ansi -std=c99 -Wall Test.o PhotoLab.o FileIO.o Image.o -L. -lfilter -o PhotoLab_v3 -lm
gcc -ansi -std=c99 -Wall -c -DDEBUG  -c PhotoLab_v3.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall -c -DDEBUG  -c Test.c -o Test_DEBUG.o
gcc -ansi -std=c99 -Wall PhotoLab_DEBUG.o FileIO.o Image.o Test_DEBUG.o -L. -lfilter -o PhotoLabTest -lm
]0;sdbrione@crystalcove:hw4[sdbrione@crystalcove hw4]$ ./Pho
PhotoLabTest* PhotoLab_v3*  
]0;sdbrione@crystalcove:hw4[sdbrione@crystalcove hw4]$ ./PhotoLab_v3 

-------------------------
 1: Load a PPM image
 2: Save image in PPM and JPEG format
 3: Run aging
 4: Run edge detection filter
 5: Run sharpen filter
 6: Run noise filter
 7: Run posterize filter
 8: Run negative filter
 9: Enlarge image
 10: Create square (crop) image
 11: Adjust brightness and contrast
22: Test all functions
99: Exit

-------------------------
Please make your choice: 22
AutoTest finished successfully.

-------------------------
 1: Load a PPM image
 2: Save image in PPM and JPEG format
 3: Run aging
 4: Run edge detection filter
 5: Run sharpen filter
 6: Run noise filter
 7: Run posterize filter
 8: Run negative filter
 9: Enlarge image
 10: Create square (crop) image
 11: Adjust brightness and contrast
22: Test all functions
99: Exit

-------------------------
Please make your choice: 99
You exit the program.
]0;sdbrione@crystalcove:hw4[sdbrione@crystalcove hw4]$ valgrind --leak-check-a[K[K=full ./Pho
PhotoLab_DEBUG.o    PhotoLabTest*       PhotoLab_v3.c       
PhotoLab.o          PhotoLab_v3*        PhotoLab_v3.script  
]0;sdbrione@crystalcove:hw4[sdbrione@crystalcove hw4]$ valgrind --leak-check=full ./PhotoLabTest
==12577== Memcheck, a memory error detector
==12577== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==12577== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==12577== Command: ./PhotoLabTest
==12577== 
LoadImage & SaveImage tested!

Aging tested!

Sharpen tested!

Edge tested!

Noise tested!

Posterization tested!

Negative tested!

Enlarge tested!

Square tested!

Brightness and Contrast tested!

AutoTest finished successfully.
==12577== 
==12577== HEAP SUMMARY:
==12577==     in use at exit: 0 bytes in 0 blocks
==12577==   total heap usage: 76 allocs, 76 frees, 11,212,608 bytes allocated
==12577== 
==12577== All heap blocks were freed -- no leaks are possible
==12577== 
==12577== For counts of detected and suppressed errors, rerun with: -v
==12577== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;sdbrione@crystalcove:hw4[sdbrione@crystalcove hw4]$ make clean
rm -f *.o *.jpg PhotoLab_v3 PhotoLabTest edge.ppm sharpen.ppm posterize.ppm aging.ppm negative.ppm noise.ppm square.ppm brightnessandcontrast.ppm enlarge.ppm original.ppm libfilter.a libFileIO.a
rm -f PhotoLab_v3
rm -f PhotoLabTest
]0;sdbrione@crystalcove:hw4[sdbrione@crystalcove hw4]$ exit
exit

Script done on Sun 07 Mar 2021 05:23:22 PM PST
