Script started on Mon 15 Mar 2021 08:27:58 PM PDT
]0;sdbrione@crystalcove:hw5[sdbrione@crystalcove hw5]$ make
gcc -ansi -std=c99 -Wall -c -g TicTacWowWeeWow.c -o TicTacWowWeeWow.o
gcc -ansi -std=c99 -Wall -c -g Settings.c -o Settings.o
gcc -ansi -std=c99 -Wall -c -g Game.c -o Game.o
gcc -ansi -std=c99 -Wall -c -g FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c -g Board.c -o Board.o
gcc -ansi -std=c99 -Wall -c -g AI.c -o AI.o
ar rc libAI.a AI.o
ranlib libAI.a
gcc -ansi -std=c99 -Wall -g TicTacWowWeeWow.o Settings.o Game.o FileIO.o Board.o -L. -lAI -o TicTacWowWeeWow
]0;sdbrione@crystalcove:hw5[sdbrione@crystalcove hw5]$ makevalgrind --vgdb=yes --vgdb-error=0 ./TicTacWowWeeWow[29Gscript TicTacWowWee[K[29Gvi TicTacWowWeeWow.txt[29G./TicTacWowWeeWow[K[29Gvi Game.c[K[32GTicTacWowWeeWow.c[32GSettings.h[Kc[32GFileIO.h[Kc[32GBoard.h[Kc[32GAI.h[Kc[29Gls -l[Ka[Kmake clean[29Gvi Makefile[29Grm *.txt[K[29Gvi Game.h[30Galgrind --leak-check=full --leak-resolution=high --track-origins=y es ./TicTacWowWeeWow[A[30Gi Board.g[K[95G e[K[A[39G[30Galgrind --leak-check=full --leak-resolution=high --track-origins=y es ./TicTacWowWeeWow
==36629== Memcheck, a memory error detector
==36629== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==36629== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==36629== Command: ./TicTacWowWeeWow
==36629== 
[H[2J[H[2JWelcome to Welcome to Secure-Tic-Tac-Whoa!
1: Start New Game (Human v. Human)
2: Start New Game (Human v. AI)
3: Game Settings
4: Exit Game
Choose Option: 3
[H[2J[H[2J[H[2JPlayer 1:
	1: Text Color
	2: Symbol(Default 'X')
Player 2:
	3: Text Color
	4: Symbol(Default 'O')
5: Back
Choose Option: 1
[H[2JPlayer 1 Color Options:
	97: Default	
31: Red		32: Green
33: Yellow	34: Blue
35: Magenta	36: Cyan
Choose Option: 33
[H[2JPlayer 1:
	1: Text Color
	2: Symbol(Default 'X')
Player 2:
	3: Text Color
	4: Symbol(Default 'O')
5: Back
Choose Option: 2
[H[2JPlayer 1 Symbol: F
[H[2JPlayer 1:
	1: Text Color
	2: Symbol(Default 'X')
Player 2:
	3: Text Color
	4: Symbol(Default 'O')
5: Back
Choose Option: 3
[H[2JPlayer 2 Color Options:
	97: Default	
31: Red		32: Green
33: Yellow	34: Blue
35: Magenta	36: Cyan
Choose Option: 35
[H[2JPlayer 1:
	1: Text Color
	2: Symbol(Default 'X')
Player 2:
	3: Text Color
	4: Symbol(Default 'O')
5: Back
Choose Option: 4
[H[2JPlayer 2 Symbol: A
[H[2JPlayer 1:
	1: Text Color
	2: Symbol(Default 'X')
Player 2:
	3: Text Color
	4: Symbol(Default 'O')
5: Back
Choose Option: 5
[H[2JWelcome to Secure-Tic-Tac-Whoa!
1: Start New Game (Human v. Human)
2: Start New Game (Human v. AI)
3: Game Settings
4: Exit Game
Choose Option: 2
[H[2JPlease choose opponent's AI level:
1: Level 1 (Inky)
2: Level 2 (Blinky)
3: Level 3 (Pinky)
Choose option: 1

C [0m [0m|[0m [0m|[0m 
[0m  ------
B [0m [0m|[0m [0m|[0m 
[0m  ------
A [0m [0m|[0m [0m|[0m 
[0m  1 2 3 
Player F, please choose your move: A1

[H[2JPlayer F chose A1
C [0m [0m|[0m [0m|[0m 
[0m  ------
B [0m [0m|[0m [0m|[0m 
[0m  ------
A [33mF[0m|[0m [0m|[0m 
[0m  1 2 3 
[H[2JPlayer A chose: C1
C [35mA[0m|[0m [0m|[0m 
[0m  ------
B [0m [0m|[0m [0m|[0m 
[0m  ------
A [33mF[0m|[0m [0m|[0m 
[0m  1 2 3 
Input "99" for take back moves.
Player F, please choose your move: A2

[H[2JPlayer F chose A2
C [35mA[0m|[0m [0m|[0m 
[0m  ------
B [0m [0m|[0m [0m|[0m 
[0m  ------
A [33mF[0m|[33mF[0m|[0m 
[0m  1 2 3 
[H[2JPlayer A chose: C2
C [35mA[0m|[35mA[0m|[0m 
[0m  ------
B [0m [0m|[0m [0m|[0m 
[0m  ------
A [33mF[0m|[33mF[0m|[0m 
[0m  1 2 3 
Input "99" for take back moves.
Player F, please choose your move: A3

[H[2JPlayer F chose A3
C [35mA[0m|[35mA[0m|[0m 
[0m  ------
B [0m [0m|[0m [0m|[0m 
[0m  ------
A [33mF[0m|[33mF[0m|[33mF
[0m  1 2 3 
Player F won!!

Would you like to save the game's replay?
1: Yes		2: No
Choose Option: 1
Name file: test    TEST
[H[2JWelcome to Secure-Tic-Tac-Whoa!
1: Start New Game (Human v. Human)
2: Start New Game (Human v. AI)
3: Game Settings
4: Exit Game
Choose Option: 4
==36629== 
==36629== HEAP SUMMARY:
==36629==     in use at exit: 0 bytes in 0 blocks
==36629==   total heap usage: 31 allocs, 31 frees, 3,586 bytes allocated
==36629== 
==36629== All heap blocks were freed -- no leaks are possible
==36629== 
==36629== For counts of detected and suppressed errors, rerun with: -v
==36629== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;sdbrione@crystalcove:hw5[sdbrione@crystalcove hw5]$ exit
exit

Script done on Mon 15 Mar 2021 08:29:01 PM PDT
